"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '13%27dbe@$4vb-hkrp$k!jphn&%@7^%0ipy+sj$zi6d7%s$os('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'newapp',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
#Driver={ODBC Driver 18 for SQL Server};Server=tcp:myfirst-saikrosuri.database.windows.net,1433;Database=testing;Uid=saikrosuri;
#Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'testing',
        'USER': 'saikrosuri@myfirst-saikrosuri',
        'PASSWORD': 'Sai@8900',
        'HOST': 'myfirst-saikrosuri.database.windows.net',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'Encrypt': 'yes',
            'TrustServerCertificate': 'no',
            'Connection Timeout': 60,
        },
    }
}

if DEBUG:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
    AZURE_ACCOUNT_NAME = 'mediafilesstorage8900'
    AZURE_ACCOUNT_KEY = 'e0KlI685sKVE6TIxkeX42vB91KTabQ8++Vd/8Q86vYDaHaLkKVsrYiuUe6nJlPO6i5P1rmOqrI2k+ASttZX1AQ=='
    AZURE_CONTAINER = 'media'
    MEDIA_URL = f'https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/'



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

if DEBUG:
    STATIC_URL = '/static/'
    STATICFILES_DIR = os.path.join(BASE_DIR, '/static')
else:
    # Use django-storages for static too
    STATICFILES_DIR = 'storages.backends.azure_storage.AzureStorage'
    AZURE_ACCOUNT_NAME = "mediafilesstorage8900"
    AZURE_ACCOUNT_KEY = "e0KlI685sKVE6TIxkeX42vB91KTabQ8++Vd/8Q86vYDaHaLkKVsrYiuUe6nJlPO6i5P1rmOqrI2k+ASttZX1AQ=="
    AZURE_STATIC_CONTAINER = "static"
    STATIC_ROOT = os.path.join(BASE_DIR, 'admin')
    STATIC_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_STATIC_CONTAINER}/"
