# Generated by Django 4.2.24 on 2025-09-19 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ghd_pipe_inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sampler', models.CharField(max_length=50)),
                ('sample_date', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.CharField(max_length=50)),
                ('leak_location', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('time_notified_tva', models.DateField()),
                ('wts_shutdown_time', models.DateField()),
                ('action_taken', models.CharField(max_length=255)),
            ],
        ),
    ]
