# Generated by Django 4.2.24 on 2025-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_ghd_pipe_inspection_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghd_pipe_inspection',
            name='data_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
