# Generated by Django 4.2 on 2025-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_ghd_pipe_inspection_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghd_pipe_inspection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
